!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (bugfix_servletAD) -  4 Jan 2024 17:44
!
!  Differentiation of euler_flux in forward (tangent) mode:
!   variations   of useful results: flux
!   with respect to varying inputs: q
!   RW status of diff variables: q:in flux:out
SUBROUTINE EULER_FLUX_DV(q, qd, flux, fluxd, nbdirs)
  USE DIFFSIZES
!  Hint: nbdirsmax should be the maximum number of differentiation directions
  IMPLICIT NONE
! primitive state [\rho, u, p]
  REAL :: q(3)
  REAL :: qd(nbdirsmax, 3)
! euler flux [\rho * u, \rho u^2 + p, (\rho * E + p ) u]
  REAL :: flux(3)
  REAL :: fluxd(nbdirsmax, 3)
  REAL, PARAMETER :: r=287.39
  REAL, PARAMETER :: gamma_air=1.4
  REAL :: t
  REAL :: rhoh
  REAL, DIMENSION(nbdirsmax) :: rhohd
  INTEGER :: nd
  INTEGER :: nbdirs
! T = p / \rho * R
  t = q(3)/r*q(1)
  rhoh = q(3)*gamma_air/(gamma_air-1) + 0.5*q(1)*q(2)*q(2)
! rho * u
  fluxd = 0.0
  DO nd=1,nbdirs
! \rho H = p * \gamma / (\gamma - 1) + 1/2 \rho u^2
    rhohd(nd) = gamma_air*qd(nd, 3)/(gamma_air-1) + 0.5*(q(2)**2*qd(nd, &
&     1)+q(1)*2*q(2)*qd(nd, 2))
    fluxd(nd, 1) = q(2)*qd(nd, 1) + q(1)*qd(nd, 2)
! \rho u^2 + p
    fluxd(nd, 2) = q(2)**2*qd(nd, 1) + q(1)*2*q(2)*qd(nd, 2) + qd(nd, 3)
! u * \rho H
    fluxd(nd, 3) = rhoh*qd(nd, 2) + q(2)*rhohd(nd)
  END DO
  flux(1) = q(1)*q(2)
  flux(2) = q(1)*q(2)*q(2) + q(3)
  flux(3) = q(2)*rhoh
END SUBROUTINE EULER_FLUX_DV

