!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (bugfix_servletAD) -  4 Jan 2024 17:44
!
!  Differentiation of foo in reverse (adjoint) mode:
!   gradient     of useful results: y
!   with respect to varying inputs: x y
!   RW status of diff variables: x:out y:in-out
SUBROUTINE FOO_B(n, x, xb, y, yb)
  IMPLICIT NONE
  INTEGER :: n
  REAL :: x(n)
  REAL :: xb(n)
  REAL :: y(n)
  REAL :: yb(n)
  INTEGER :: i
  REAL :: max_value
  REAL :: max_valueb
  INTEGER*4 :: branch
  max_value = x(1)
  DO i=1,n
    IF (max_value .LT. x(i)) THEN
      max_value = x(i)
      CALL PUSHCONTROL1B(1)
    ELSE
      CALL PUSHCONTROL1B(0)
    END IF
  END DO
  xb = 0.0
  max_valueb = 0.0
  DO i=n,1,-1
    xb(i) = xb(i) + yb(i)/max_value
    max_valueb = max_valueb - x(i)*yb(i)/max_value**2
    yb(i) = 0.0
  END DO
  DO i=n,1,-1
    CALL POPCONTROL1B(branch)
    IF (branch .NE. 0) THEN
      xb(i) = xb(i) + max_valueb
      max_valueb = 0.0
    END IF
  END DO
  xb(1) = xb(1) + max_valueb
END SUBROUTINE FOO_B
