!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (bugfix_servletAD) -  4 Jan 2024 17:44
!
!  Differentiation of stencil in forward (tangent) mode:
!   variations   of useful results: res
!   with respect to varying inputs: u
!   RW status of diff variables: res:out u:in
SUBROUTINE STENCIL_D(n, coeff, u, ud, res, resd)
  IMPLICIT NONE
  INTEGER :: n
  REAL :: coeff(3)
  REAL :: u(n)
  REAL :: ud(n)
  REAL :: res(n)
  REAL :: resd(n)
  INTEGER :: i
! BC left
  resd = 0.0
  resd(1) = coeff(2)*ud(1) + coeff(3)*ud(2)
  res(1) = coeff(2)*u(1) + coeff(3)*u(2)
! BC right
  resd(n) = coeff(1)*ud(n-1) + coeff(2)*ud(n)
  res(n) = coeff(1)*u(n-1) + coeff(2)*u(n)
  DO i=2,n-1
    resd(i) = coeff(1)*ud(i-1) + coeff(2)*ud(i) + coeff(3)*ud(i+1)
    res(i) = coeff(1)*u(i-1) + coeff(2)*u(i) + coeff(3)*u(i+1)
  END DO
END SUBROUTINE STENCIL_D

